# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{saml2ruby}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sean Cashin"]
  s.date = %q{2010-02-16}
  s.description = %q{Part of the OpenSSO extension set.  Writting by the wonderful guys over at Sun.  Moved it over to a github repo and turned it into a rubygem.}
  s.email = ["scashin133@gmail.com"]
  s.extra_rdoc_files = [
    "README",
     "TODO"
  ]
  s.files = [
    "README",
     "Rakefile",
     "lib/saml2ruby.rb",
     "lib/saml_2_ruby.rb",
     "lib/saml_2_ruby/relying_party.rb",
     "lib/saml_2_ruby/version.rb",
     "lib/saml_2_ruby/xml_sec.rb"
  ]
  s.homepage = %q{http://github.com/scashin133/saml2ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby implementation of the SAML 2.0 Specification}
  s.test_files = [
    "test/xml_sec_test.rb",
     "examples/rails/SimpleSAMLRP/app/controllers/account_controller.rb",
     "examples/rails/SimpleSAMLRP/app/controllers/application.rb",
     "examples/rails/SimpleSAMLRP/app/helpers/account_helper.rb",
     "examples/rails/SimpleSAMLRP/app/helpers/application_helper.rb",
     "examples/rails/SimpleSAMLRP/config/boot.rb",
     "examples/rails/SimpleSAMLRP/config/environment.rb",
     "examples/rails/SimpleSAMLRP/config/environments/development.rb",
     "examples/rails/SimpleSAMLRP/config/environments/production.rb",
     "examples/rails/SimpleSAMLRP/config/environments/test.rb",
     "examples/rails/SimpleSAMLRP/config/routes.rb",
     "examples/rails/SimpleSAMLRP/public/dispatch.rb",
     "examples/rails/SimpleSAMLRP/test/functional/account_controller_test.rb",
     "examples/rails/SimpleSAMLRP/test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<XMLCanonicalizer>, [">= 1.0.1"])
    else
      s.add_dependency(%q<XMLCanonicalizer>, [">= 1.0.1"])
    end
  else
    s.add_dependency(%q<XMLCanonicalizer>, [">= 1.0.1"])
  end
end

